language: go
go:
 - 1.3.3

install:
 - go get code.google.com/p/go.tools/cmd/vet
 - go get -t -v ./...
 - touch $HOME/.pulsecli 

script:
 - go tool vet -all .
 - go build ./...
 - go test -race -v ./...
